# Generate build/version_gen.h from Directory.Build.props.
#
# The native binaries' VERSIONINFO has to agree with the released SDK
# version, and the only way to guarantee that is to read the one place
# the version already lives rather than repeating it in a header someone
# has to remember to bump.
#
# Emitted into build/ (gitignored) and picked up by rc.exe through its
# include path, so nothing generated is ever committed.

param(
    [Parameter(Mandatory = $true)][string]$PropsPath,
    [Parameter(Mandatory = $true)][string]$OutPath
)

$ErrorActionPreference = 'Stop'

[xml]$props = Get-Content -LiteralPath $PropsPath
$version = ($props.Project.PropertyGroup.Version | Where-Object { $_ }) | Select-Object -First 1
if (-not $version) { throw "No <Version> found in $PropsPath" }

# Accept 1.7.3 or 1.7.3.4; the resource always carries four fields.
$parts = "$version".Trim().Split('.')
if ($parts.Count -lt 3) { throw "Version '$version' is not major.minor.patch" }
$major, $minor, $patch = [int]$parts[0], [int]$parts[1], [int]$parts[2]

$header = @"
/* GENERATED by scripts/gen_version.ps1 from Directory.Build.props.
   Do not edit, and do not commit: build/ is gitignored. */
#pragma once
#define HM_VER_MAJOR  $major
#define HM_VER_MINOR  $minor
#define HM_VER_PATCH  $patch
#define HM_VER_STRING "$major.$minor.$patch.0"
"@

$dir = Split-Path -Parent $OutPath
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force $dir | Out-Null }
Set-Content -LiteralPath $OutPath -Value $header -Encoding ascii
Write-Host "  version_gen.h -> $major.$minor.$patch.0"
